# Global settings applied to the whole site.
[build]
  command = "hugo"
  publish = "public"
  HUGO_ENV = "preview"

# The default version you use for production if you don't use context below
[build.environment]
  HUGO_VERSION = "0.32.3"

[context.branch-deploy]
  # command = "ls -l ./content/posts && sh updateDate.sh && ls -l ./content/posts && hugo"
  # command = "node ./scripts/test-env.js && hugo"
  command = "node ./scripts/create-env.js && hugo"

# build a preview of the site (Drafts and Future dates also)
[context.deploy-preview]
  command = "hugo --buildFuture"

[context.production.environment]
  HUGO_VERSION = "0.32.3"
  HUGO_ENV = "production"
# you can lock a version of hugo for a deploy preview
[context.deploy-preview.environment]
  HUGO_VERSION = "0.32.3"
  HUGO_ENV = "deploy" # TEST: should be deploy or something other than production
# you can lock a version of hugo for a branch-deploy (other than previews)
[context.branch-deploy.environment]
  HUGO_VERSION = "0.32.3"
  HUGO_ENV = "development"
